// pages/report/[ticker].js — Report page with 6-tab layout and terminal aesthetics
import { useEffect, useState, useRef } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Header from '../../components/layout/Header';
import ReportTabs from '../../components/layout/ReportTabs';
import OverviewTab from '../../components/report/OverviewTab';
import FinancialsTab from '../../components/report/FinancialsTab';
import ValuationTab from '../../components/report/ValuationTab';
import ForensicsTab from '../../components/report/ForensicsTab';
import ShareholdingTab from '../../components/report/ShareholdingTab';
import RisksTab from '../../components/report/RisksTab';

export default function ReportPage() {
  const router = useRouter();
  const { ticker } = router.query;
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [tab, setTab] = useState('overview');
  const [step, setStep] = useState(0);
  const reportRef = useRef(null);

  const STEPS = [
    'Initializing network connections to Screener & Yahoo Finance...',
    'Scraping annual financials, cash flows, and balance sheets...',
    'Performing Piotroski F-Score financial health evaluation...',
    'Calculating Beneish M-Score and Altman Z-Score index components...',
    'Estimating Weighted Average Cost of Capital (WACC) & run DCF models...',
    'Generating institutional AI summary, thesis & Strategic risk matrix...'
  ];

  useEffect(() => {
    if (!ticker) return;
    generateReport();
  }, [ticker]);

  async function generateReport() {
    setLoading(true); setError(''); setData(null); setStep(0);
    const interval = setInterval(() => setStep(p => Math.min(p + 1, STEPS.length - 1)), 4000);

    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 60000);

      const res = await fetch('/api/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ticker }),
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      const text = await res.text();
      let json;
      try { json = JSON.parse(text); } catch {
        throw new Error(text ? `Invalid response: ${text.slice(0, 200)}` : 'Empty response');
      }
      if (!res.ok || !json.success) throw new Error(json.error || `Failed (${res.status})`);
      setData(json.data);
    } catch (e) {
      setError(e.name === 'AbortError' ? 'Request timed out. Try again.' : e.message);
    } finally {
      clearInterval(interval);
      setLoading(false);
    }
  }

  async function exportPDF() {
    const { default: html2canvas } = await import('html2canvas');
    const { jsPDF } = await import('jspdf');
    const el = reportRef.current;
    if (!el) return;

    // Temporarily switch to white bg for PDF
    el.style.background = '#ffffff';
    el.style.color = '#111111';

    const canvas = await html2canvas(el, { scale: 1.5, useCORS: true, backgroundColor: '#ffffff' });

    // Restore dark bg
    el.style.background = '';
    el.style.color = '';

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfW = pdf.internal.pageSize.getWidth();
    const pdfH = (canvas.height * pdfW) / canvas.width;

    pdf.setFontSize(8);
    pdf.setTextColor(100);
    pdf.text(`INSTITUTIONAL RESEARCH NOTE | ${data?.companyName || ticker} | ${new Date().toLocaleDateString()}`, 10, 8);

    let y = 12;
    const pageH = pdf.internal.pageSize.getHeight();
    while (y < pdfH + 12) {
      if (y > 12) pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, 12 - y, pdfW, pdfH);
      pdf.setFontSize(7);
      pdf.setTextColor(150);
      pdf.text('This report is generated by AI and is not investment advice. Not SEBI registered.', 10, pageH - 5);
      y += pageH - 12;
    }

    pdf.save(`${data?.companyName || ticker}_Research_Report.pdf`);
  }

  const renderTab = () => {
    if (!data) return null;
    switch (tab) {
      case 'overview': return <OverviewTab data={data} />;
      case 'financials': return <FinancialsTab data={data} />;
      case 'valuation': return <ValuationTab data={data} />;
      case 'forensics': return <ForensicsTab data={data} />;
      case 'shareholding': return <ShareholdingTab data={data} />;
      case 'risks': return <RisksTab data={data} />;
      default: return <OverviewTab data={data} />;
    }
  };

  return (
    <>
      <Head>
        <title>{ticker ? `${ticker} — Research Report | StockIQ` : 'Report | StockIQ'}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header
        companyName={data?.companyName}
        symbol={data?.symbol || ticker}
        price={data?.price}
        priceChange={data?.priceChange}
        priceChangePct={data?.priceChangePct}
        onRegenerate={generateReport}
        onExportPDF={exportPDF}
        hasData={!!data}
      />

      {/* Tabs list sits outside the inner content wrapper but aligns at 1200px max */}
      {data && !loading && !error && (
        <ReportTabs activeTab={tab} onTabChange={setTab} />
      )}

      {/* Main Grid View Container */}
      <div style={{
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '24px 16px',
        minHeight: 'calc(100vh - 120px)',
        backgroundColor: 'var(--bg-0)'
      }}>

        {/* Loading Terminal State */}
        {loading && (
          <div style={{
            maxWidth: '600px',
            margin: '80px auto 0 auto',
            padding: '24px',
            backgroundColor: 'var(--bg-1)',
            border: '1px solid var(--border-subtle)'
          }}>
            <div style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '11px',
              color: 'var(--text-1)',
              textTransform: 'uppercase',
              marginBottom: '16px',
              letterSpacing: '0.05em'
            }}>
              Terminal Analysis Log
            </div>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '20px' }}>
              {STEPS.map((s, i) => {
                const isPast = i < step;
                const isCurrent = i === step;
                return (
                  <div key={i} style={{
                    display: 'flex',
                    alignItems: 'baseline',
                    gap: '12px',
                    opacity: isPast || isCurrent ? 1 : 0.25,
                    fontSize: '12px',
                    fontFamily: 'var(--font-mono)',
                    lineHeight: 1.4
                  }}>
                    <span style={{
                      color: isPast ? 'var(--accent-green)' : isCurrent ? 'var(--accent-yellow)' : 'var(--text-2)'
                    }}>
                      {isPast ? '✓' : isCurrent ? '▪' : '○'}
                    </span>
                    <span style={{ color: 'var(--text-1)' }}>{s}</span>
                    {isPast && (
                      <span style={{ color: 'var(--accent-green)', marginLeft: 'auto', fontSize: '10px' }}>
                        OK
                      </span>
                    )}
                    {isCurrent && (
                      <span style={{ color: 'var(--accent-yellow)', marginLeft: 'auto', fontSize: '10px', animation: 'pulse 1s infinite' }}>
                        RUN
                      </span>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Progress line */}
            <div style={{
              height: '2px',
              backgroundColor: 'var(--bg-2)',
              width: '100%',
              position: 'relative'
            }}>
              <div style={{
                height: '100%',
                backgroundColor: 'var(--accent-yellow)',
                width: `${((step + 1) / STEPS.length) * 100}%`,
                transition: 'width 0.4s ease'
              }} />
            </div>
          </div>
        )}

        {/* Error Terminal Card */}
        {error && (
          <div style={{
            maxWidth: '600px',
            margin: '80px auto 0 auto',
            padding: '24px',
            backgroundColor: 'var(--bg-1)',
            border: '1px solid var(--accent-red)'
          }}>
            <div style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '11px',
              color: 'var(--accent-red)',
              textTransform: 'uppercase',
              marginBottom: '12px',
              fontWeight: 600
            }}>
              SYSTEM ERROR: ANALYSIS ABORTED
            </div>
            <p style={{
              fontSize: '13px',
              fontFamily: 'var(--font-mono)',
              color: 'var(--text-1)',
              lineHeight: 1.5,
              marginBottom: '20px'
            }}>
              {error}
            </p>
            <button
              onClick={generateReport}
              style={{
                backgroundColor: 'transparent',
                border: '1px solid var(--accent-red)',
                color: 'var(--accent-red)',
                fontFamily: 'var(--font-mono)',
                fontSize: '12px',
                padding: '8px 16px',
                cursor: 'pointer',
                transition: 'all 0.15s'
              }}
              onMouseOver={(e) => {
                e.currentTarget.style.backgroundColor = 'rgba(229, 72, 77, 0.1)';
              }}
              onMouseOut={(e) => {
                e.currentTarget.style.backgroundColor = 'transparent';
              }}
            >
              RE-RUN ANALYSIS
            </button>
          </div>
        )}

        {/* Actual Report Content */}
        {data && !loading && !error && (
          <div ref={reportRef}>
            {/* Data intelligence verification line */}
            <div style={{
              display: 'flex',
              flexWrap: 'wrap',
              gap: '16px',
              alignItems: 'baseline',
              fontFamily: 'var(--font-mono)',
              fontSize: '10px',
              color: 'var(--text-2)',
              marginBottom: '24px',
              textTransform: 'uppercase',
              letterSpacing: '0.05em'
            }}>
              <span>DATABASES:</span>
              {(data.dataSources || []).map(src => (
                <span key={src} style={{ color: 'var(--text-1)' }}>{src}</span>
              ))}
              {data.dataQuality?.screenerOk && (
                <span style={{ color: 'var(--accent-green)' }}>[10Y PL VERIFIED]</span>
              )}
            </div>

            {/* Render selected sub-panel */}
            <div style={{ marginTop: '16px' }}>
              {renderTab()}
            </div>
          </div>
        )}

      </div>
    </>
  );
}
